name: Deploy-DGS

on:
  workflow_call:
    inputs:
      projectPackage:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying ${{ inputs.projectPackage }}"
