name: Deploy-DGS

on:
  workflow_call:
    inputs:
      projectPackage:
        required: true
        type: string
        
jobs:
  runs-on: ubuntu-latest
  steps:
    runs: echo ${{ inputs.projectPackage }}
