name: CI-DGS

on:
  # push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/builddgs.yml
    with:
      project: "My Dave Project"
      
  test:
    uses: ./.github/workflows/testdgs.yml
    with:
      project: "My Dave Project"
